name: Upload
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
  commit:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      # - name: Clone target
      #   uses: actions/checkout@v2
      #   with:
      #     repository: Duncan-Ultra/github-actions-test
      # - name: Check
      #   run: |
      #     pwd
      #     ls -a
      # - name: Download artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: code-coverage
      #     path: artifact
      - name: Commit change
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://Duncan-Ultra:${{ secrets.GITHUB_TOKEN }}@github.com/Duncan-Ultra/github-actions-test.git"
          git config --global user.name "duncan@ultra.io"
          git config --global user.name "duncan-ultra"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m"Random file"
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push "https://Duncan-Ultra:${{ secrets.GITHUB_TOKEN }}@github.com/Duncan-Ultra/github-actions-test.git" master:master
      # - name: Clone target folder
      #   run: |
      #     pwd
      #     ls -a
      #     git init
      #     git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.TARGET_REPOS }}.git"
      #     git config --global user.name "duncan@ultra.io"
      #     git config --global user.name "duncan-ultra"
      #     git fetch
      #     git checkout master
      #     git branch --set-upstream-to=origin/master
      #     git pull
      #     ls -a